linters-settings:
  errcheck:
    check-type-assertions: false
    ignore:
      - logger.Sync
  govet:
    check-shadowing: true
  bodyclose:
    check-defer: false

issues:
  exclude:
    -w.Write
  exclude-rules:
    - linters:
        - unconvert
        - unused
        - errchkjson
        - gosimple
        - noctx
      text: "unnecessary conversion"
    - linters:
        - unused
      text: "const basePath is unused"
    - linters:
        - errchkjson
      text: "Error return value of encoding/json.Marshal is not checked"
    - linters:
        - gosimple
      text: "unnecessary use of fmt.Sprintf"
    - linters:
        - noctx
      text: "should rewrite http.NewRequestWithContext or add (*Request).WithContext"

linters:
  enable-all: true
  disable:
    - gochecknoglobals # Пример отключения конкретного линтера.



